from environs import Env

env = Env()
env.read_env()

# DATABASE CONFIG
DB_HOST = env.str('DB_HOST', '127.0.0.1')
DB_PORT = env.int('DB_PORT', '6379')
DB_NAME = env.str('DB_NAME', None)
DB_PASS = env.str('DB_PASS', None)
DB_CLIENT = 'Redis'

# API SERVER CONFIG
ENABLE_SERVER = True
SERVER_HOST = '0.0.0.0'
SERVER_PORT = '9870'

# SCHEDULER CONFIG
ENABLE_SCHEDULER = True
SCHEDULER_INTERVAL = 1000

# DETECTOR CONFIG
ENABLE_DETECTOR = True
DETECTOR_INTERVAL = 1000

# DETECTOR CONFIG
F_S_RATIO = 100

# FETCH STRATEGY CONFIG
SUCCESS_AWARD = 8
FAIL_PUNISH = -2
RES_RATIO = 0.8
FETCH_LIMIT = 5
